RealRegions:
  Prefix: "&fReal&eRegions &7>"
  Date-Format: "yyyy-MM-dd HH:mm:ss"
  Disable-Alert-Messages: false
  Effects:
    Particles: true
    Sounds: true
  Hooks:
    RealMines:
      Import-Mines: true
Version: 3